table Dim_Date
	lineageTag: e8665edb-45fa-4e98-873d-a185898d6ca0
	dataCategory: Time

	column 'Date Key'
		dataType: string
		lineageTag: a2557155-0e48-4df9-a34d-32d0c9929960
		summarizeBy: none
		sourceColumn: Date Key

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 0325de84-2a39-4c36-adce-d4232138de4f
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: string
		lineageTag: 6cf78c4a-29ac-4a3d-b77c-1e39b8bd3a85
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Dim_Product","TableItemName":"Product Name (clusters)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Qtr
		dataType: string
		lineageTag: 06198683-87e1-4a2e-9b6d-ff9be55d3026
		summarizeBy: none
		sourceColumn: Qtr

		annotation SummarizationSetBy = Automatic

	column 'Month No.'
		dataType: string
		lineageTag: 164a8853-ebb5-42a6-b273-ed62e7545b42
		summarizeBy: none
		sourceColumn: Month No.

		annotation SummarizationSetBy = Automatic

	column 'Is Weekend?'
		dataType: string
		lineageTag: e1c9e381-8929-4665-9a36-02e1620d47bb
		summarizeBy: none
		sourceColumn: Is Weekend?

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: eb7e922b-3b6a-4fc0-a120-9af8d17e0570
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: 263b643c-427b-4228-97c1-8d3acd067063

		level Year
			lineageTag: 8d264964-de23-4195-be70-f8fa47158851
			column: Year

		level Qtr
			lineageTag: 5880dae3-defc-433f-81c4-bc7030b2b862
			column: Qtr

		level 'Month Name'
			lineageTag: a185fc5a-da21-4ac0-bbb3-777a978ea07e
			column: 'Month Name'

	partition Dim_Date = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents("C:\Users\ryu10\OneDrive\Udemy\Power BI\Independent Projects for Portfolio\Datasets\AI generated retail_dataset_500k\dim_date.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"day_of_month", Int64.Type}, {"day_of_week", Int64.Type}, {"is_weekend", Int64.Type}, {"is_holiday", Int64.Type}}),
				
				    // Added "Q" as prefix for better usability
				    #"Added Prefix" = Table.TransformColumns(#"Changed Type", {{"quarter", each "Q" & Text.From(_, "en-US"), type text}}),
				
				    // Removed not req fields
				    #"Removed Other Columns" = Table.SelectColumns(#"Added Prefix",{"date_key", "date", "year", "quarter", "month", "is_weekend"}),
				
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Other Columns",{
				        {"is_weekend", type text},
				        {"month", type text}
				        }),
				
				    // Replacing 1 and 0 with "Yes" & "No"
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","1","Yes",Replacer.ReplaceText,{"is_weekend"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","0","No",Replacer.ReplaceText,{"is_weekend"}),
				
				    // Month name in MMM format
				    #"Added Custom Col" = Table.AddColumn(#"Replaced Value1", "Month Name", each Date.ToText([date], "MMM")),
				
				    #"Renamed Columns" = Table.RenameColumns(#"Added Custom Col",{{"date_key", "Date Key"}, {"date", "Date"}, {"year", "Year"}, {"quarter", "Qtr"}, {"month", "Month No."}, {"is_weekend", "Is Weekend?"}}),
				
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns",{ 
				            {"Year", type text}, 
				            {"Date Key", type text}
				        })
				in
				    #"Changed Type2"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Dim_Product","TableItemName":"Product Name (clusters)","ObjectType":4},"LinkType":"UsedInGroup"}]

