table Dim_Customer
	lineageTag: 6f6ec73e-4c81-4175-a7f7-796269f7b361

	column 'Customer ID'
		dataType: string
		isHidden
		lineageTag: 5ff2b9ff-3d77-450c-b491-49898e5d6a46
		summarizeBy: none
		sourceColumn: Customer ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 03657794-7155-4519-9210-ccf0cf67a1f5
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 6089742a-e91d-4575-8be2-74a1f6229bbf
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column DOB
		dataType: dateTime
		formatString: Long Date
		lineageTag: 86333587-38ae-4f5f-ab6e-025ebd0b15a6
		summarizeBy: none
		sourceColumn: DOB

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Registration Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: f34db09a-3bec-45dc-8151-47a7f3b861ae
		summarizeBy: none
		sourceColumn: Registration Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Loyalty Tier'
		dataType: string
		lineageTag: fd858bcb-e261-4523-8685-143420bc803a
		summarizeBy: none
		sourceColumn: Loyalty Tier

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: c5d52e59-4198-49ac-8400-b5f3139b7bee
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column 'Mobile No.'
		dataType: string
		lineageTag: 48551b32-8767-4107-9df7-5399f284b764
		summarizeBy: none
		sourceColumn: Mobile No.

		annotation SummarizationSetBy = Automatic

	column 'Customer City'
		dataType: string
		lineageTag: 059a1258-6f13-46bd-95a6-b21f40abab60
		dataCategory: City
		summarizeBy: none
		sourceColumn: Customer City

		annotation SummarizationSetBy = Automatic

	column Pincode
		dataType: string
		lineageTag: a5017517-1648-42b0-828a-5908a52b3a28
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: Pincode

		annotation SummarizationSetBy = Automatic

	column 'Customer State'
		dataType: string
		lineageTag: 8f39eb9b-17e5-46f3-8526-3dd5cfb2e48a
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: Customer State

		annotation SummarizationSetBy = Automatic

	hierarchy 'Customer Address Hierarchy'
		lineageTag: 92b98cde-c83c-4f6b-99d9-2aea1795fd72

		level 'Customer State'
			lineageTag: 29dfff51-8f30-454c-b600-6c2798d75f69
			column: 'Customer State'

		level 'Customer City'
			lineageTag: ecfadbed-f8c8-47fc-877b-fd8f85582407
			column: 'Customer City'

		level Pincode
			lineageTag: 18935fe9-d3c9-4176-ad89-8765737c034b
			column: Pincode

	partition Dim_Customer = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents("C:\Users\ryu10\OneDrive\Udemy\Power BI\Independent Projects for Portfolio\Datasets\AI generated retail_dataset_500k\dim_customers.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				
				    // Default datatypes application by Power BI to appropriate types
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"customer_name", type text}, {"gender", type text}, {"birth_date", type date}, {"join_date", type date}, {"loyalty_tier", type text}, {"email", type text}, {"phone", Int64.Type}, {"city", type text}, {"state", type text}, {"postal_code", Int64.Type}}),
				
				    // Renamed the fields as per requirement
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{
				        {"customer_id", "Customer ID"}, 
				        {"customer_name", "Customer Name"}, 
				        {"gender", "Gender"}, 
				        {"birth_date", "DOB"}, 
				        {"join_date", "Registration Date"}, 
				        {"loyalty_tier", "Loyalty Tier"}, 
				        {"email", "Email"}, 
				        {"phone", "Mobile No."}, 
				        {"city", "Customer City"}, 
				        {"state", "Customer State"}, 
				        {"postal_code", "Pincode"}
				        }),
				
				    // Excplicity changing data types as needed
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Mobile No.", type text}, {"Pincode", type text}}),
				
				    // Replaced F -> Female
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","F","Female",Replacer.ReplaceText,{"Gender"}),
				
				    // Replaced U -> Unknown
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","U","Unknown",Replacer.ReplaceText,{"Gender"}),
				
				    // Replaced M -> Male
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","M","Male",Replacer.ReplaceText,{"Gender"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Replaced Value2",{"Customer State"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"Customer City"}, #"City - State Lookup Table", {"Store City"}, "City - State Lookup Table", JoinKind.Inner),
				    #"Expanded City - State Lookup Table" = Table.ExpandTableColumn(#"Merged Queries", "City - State Lookup Table", {"Store State"}, {"Store State"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded City - State Lookup Table",{{"Store State", "Customer State"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns1",{"Customer ID", "Customer Name", "Gender", "DOB", "Registration Date", "Loyalty Tier", "Email", "Mobile No.", "Customer City", "Customer State", "Pincode"})
				in
				    #"Reordered Columns"
				```

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

