table Fact_Sales
	lineageTag: efbfc5b0-f2d2-493b-ab3e-28b74a883acd

	column 'Order ID'
		dataType: string
		isHidden
		lineageTag: 00bdad7e-a887-42c1-b019-d7422f7efbf3
		summarizeBy: none
		sourceColumn: Order ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Order Date Key'
		dataType: string
		lineageTag: d9ae79c4-8af3-4207-ab47-da12c1a3528a
		summarizeBy: none
		sourceColumn: Order Date Key

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4018878a-9c81-43c5-a961-d17c7cd08734
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Delivery Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 183d0db6-1526-44c5-837f-365062d0ee11
		summarizeBy: none
		sourceColumn: Delivery Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Customer ID'
		dataType: string
		isHidden
		lineageTag: 34a05cc3-3dda-4bca-b097-53053c263351
		summarizeBy: none
		sourceColumn: Customer ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		isHidden
		lineageTag: 1d52ad04-12fe-41d5-8589-6b0ee8a9d7e3
		summarizeBy: none
		sourceColumn: Product ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Store ID'
		dataType: string
		isHidden
		lineageTag: 225ac973-153d-4bb2-92f0-8ac3765b1197
		summarizeBy: none
		sourceColumn: Store ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sales Channel'
		dataType: string
		lineageTag: b7c9cb7b-6878-44f0-8632-209c328a04b5
		summarizeBy: none
		sourceColumn: Sales Channel

		annotation SummarizationSetBy = Automatic

	column 'Payment Type'
		dataType: string
		lineageTag: c267a9bc-839b-4dd1-bae7-80e52a16281b
		summarizeBy: none
		sourceColumn: Payment Type

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: #,0
		lineageTag: 45e14636-ba05-4eea-859e-994b9dcbf340
		summarizeBy: sum
		sourceColumn: Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: decimal
		lineageTag: 8e899ac7-2902-495f-bbe2-7722726216c8
		summarizeBy: sum
		sourceColumn: Unit Price

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Discount %'
		dataType: double
		lineageTag: 5c0307e9-c832-4ec1-b286-a145dcd895da
		summarizeBy: sum
		sourceColumn: Discount %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Fact_Sales","TableItemName":"Discount % (groups)","ObjectType":4},"LinkType":"UsedInGroup"},{"LinkTarget":{"TableName":"Dim_Product","TableItemName":"Product Name (clusters)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Tax
		dataType: decimal
		lineageTag: 5e70c74f-0fdd-4406-bcb6-971e394b1788
		summarizeBy: sum
		sourceColumn: Tax

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Shipping Cost'
		dataType: decimal
		lineageTag: 237d4407-22c6-4eaa-9439-f672f655e61a
		summarizeBy: sum
		sourceColumn: Shipping Cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Amount'
		dataType: decimal
		isHidden
		lineageTag: c3fa1074-b663-4e42-aabf-a8df4d6f5ab3
		summarizeBy: sum
		sourceColumn: Total Amount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Promo ID'
		dataType: string
		isHidden
		lineageTag: 2747e460-3520-4564-99ab-667fe5364660
		summarizeBy: none
		sourceColumn: Promo ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Coupon Code'
		dataType: string
		lineageTag: 0400f458-234a-46a5-92bc-a88ccf9df858
		summarizeBy: none
		sourceColumn: Coupon Code

		annotation SummarizationSetBy = Automatic

	column Returned?
		dataType: string
		lineageTag: 38ef13bb-beac-4beb-a042-6b2ccaa6fecf
		summarizeBy: none
		sourceColumn: Returned?

		annotation SummarizationSetBy = Automatic

	column 'Return Reason'
		dataType: string
		lineageTag: f105a878-39cc-4667-a935-bbfdddba179d
		summarizeBy: none
		sourceColumn: Return Reason

		annotation SummarizationSetBy = Automatic

	column Device
		dataType: string
		lineageTag: 39ff8e1b-56f7-4f36-b936-037171139464
		summarizeBy: none
		sourceColumn: Device

		annotation SummarizationSetBy = Automatic

	column 'Discount % (groups)' =
			SWITCH(
				TRUE,
				ISBLANK('Fact_Sales'[Discount %]),
				"(Blank)",
				'Fact_Sales'[Discount %] IN {0,
					0.05,
					0.075,
					0.1,
					0.15,
					0.2,
					0.225,
					0.25},
				"<=25%",
				'Fact_Sales'[Discount %] IN {0.3,
					0.375,
					0.45,
					0.5},
				"<=50%",
				'Fact_Sales'[Discount %] IN {0.75},
				">50%",
				"Other"
			)
		lineageTag: 7042ad3e-9a9a-4277-a63a-950994bcac01
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Fact_Sales"
				          }
				        },
				        "Property": "Discount %"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"s","Entity":"Fact_Sales"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"Discount %"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"<=25%","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"Discount %"}}],"Values":[[{"Literal":{"Value":"0D"}}],[{"Literal":{"Value":"0.05D"}}],[{"Literal":{"Value":"0.075D"}}],[{"Literal":{"Value":"0.1D"}}],[{"Literal":{"Value":"0.15D"}}],[{"Literal":{"Value":"0.2D"}}],[{"Literal":{"Value":"0.225D"}}],[{"Literal":{"Value":"0.25D"}}]]}}},{"DisplayName":"<=50%","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"Discount %"}}],"Values":[[{"Literal":{"Value":"0.3D"}}],[{"Literal":{"Value":"0.375D"}}],[{"Literal":{"Value":"0.45D"}}],[{"Literal":{"Value":"0.5D"}}]]}}},{"DisplayName":">50%","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"Discount %"}}],"Values":[[{"Literal":{"Value":"0.75D"}}]]}}},{"DisplayName":"Other"}]}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents("C:\Users\ryu10\OneDrive\Udemy\Power BI\Independent Projects for Portfolio\Datasets\AI generated retail_dataset_500k\sales_fact.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", Int64.Type}, {"order_date_key", Int64.Type}, {"order_time", type text}, {"customer_id", type text}, {"product_id", type text}, {"store_id", type text}, {"sales_channel", type text}, {"payment_type", type text}, {"quantity", Int64.Type}, {"unit_price", type number}, {"discount_pct", type number}, {"tax", type number}, {"shipping_cost", type number}, {"total_amount", type number}, {"promo_id", type text}, {"coupon_code", type text}, {"returned", Int64.Type}, {"return_reason", type text}, {"delivery_date", type date}, {"device", type text}}),
				
				    // Removing empty and null Customer IDs
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [customer_id] <> null and [customer_id] <> ""),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows", {"order_id"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Duplicates",{{"order_date_key", type text}, {"order_id", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"order_id", "Order ID"}, {"order_date_key", "Order Date Key"}}),
				    #"Added Custom Column" = Table.AddColumn(#"Renamed Columns", "Custom", each Text.Combine({Date.ToText(Date.From([Order Date Key]), "MM"), "/", Date.ToText(Date.From([Order Date Key]), "dd"), "/", Date.ToText(Date.From([Order Date Key]), "yyyy")}), type text),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom Column",{{"Custom", type date}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type2",{"Order ID", "Order Date Key", "Custom", "order_time", "customer_id", "product_id", "store_id", "sales_channel", "payment_type", "quantity", "unit_price", "discount_pct", "tax", "shipping_cost", "total_amount", "promo_id", "coupon_code", "returned", "return_reason", "delivery_date", "device"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"order_time"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"Custom", "Order Date"}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns1",{"Order ID", "Order Date Key", "Order Date", "delivery_date", "customer_id", "product_id", "store_id", "sales_channel", "payment_type", "quantity", "unit_price", "discount_pct", "tax", "shipping_cost", "total_amount", "promo_id", "coupon_code", "returned", "return_reason", "device"}),
				    
				    #"Renamed Columns2" = Table.RenameColumns(#"Reordered Columns1",{{"delivery_date", "Delivery Date"}, {"customer_id", "Customer ID"}, {"product_id", "Product ID"}, {"store_id", "Store ID"}, {"sales_channel", "Sales Channel"}, {"payment_type", "Payment Type"}, {"quantity", "Quantity"}, {"unit_price", "Unit Price"}, {"discount_pct", "Discount %"}, {"tax", "Tax"}, {"shipping_cost", "Shipping Cost"}, {"total_amount", "Total Amount"}, {"promo_id", "Promo ID"}, {"coupon_code", "Coupon Code"}, {"returned", "Returned?"}, {"return_reason", "Return Reason"}, {"device", "Device"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Returned?", type text}}),
				
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type3","0","No",Replacer.ReplaceText,{"Returned?"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","1","Yes",Replacer.ReplaceText,{"Returned?"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Value1",{{"Total Amount", Currency.Type}, {"Shipping Cost", Currency.Type}, {"Tax", Currency.Type}, {"Unit Price", Currency.Type}}),
				    #"Divided Column" = Table.TransformColumns(#"Changed Type4", {{"Discount %", each _ / 100, type number}}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Divided Column",{{"Discount %", Percentage.Type}})
				in
				    #"Changed Type5"
				```

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Dim_Product","TableItemName":"Product Name (clusters)","ObjectType":4},"LinkType":"UsedInGroup"}]

